REM Удаление файлов в "XPression" лежащие более 14 дней
FORFILES /P D:\Channel_Programm_Air\XPression\DAY\01_п­ў ам\ /M *.* /S /D -14 /C "cmd if @isdir==FALSE /C del "@FILE""
FORFILES /P D:\Channel_Programm_Air\XPression\DAY\02_дҐўа «м\ /M *.* /S /D -14 /C "cmd if @isdir==FALSE /C del "@FILE""
FORFILES /P D:\Channel_Programm_Air\XPression\DAY\03_¬ ав\ /M *.* /S /D -14 /C "cmd if @isdir==FALSE /C del "@FILE""
FORFILES /P D:\Channel_Programm_Air\XPression\DAY\04_ ЇаҐ«м\ /M *.* /S /D -14 /C "cmd if @isdir==FALSE /C del "@FILE"" 
FORFILES /P D:\Channel_Programm_Air\XPression\DAY\05_¬ ©\ /M *.* /S /D -14 /C "cmd if @isdir==FALSE /C del "@FILE"" 
FORFILES /P D:\Channel_Programm_Air\XPression\DAY\06_Ёо­м\ /M *.* /S /D -14 /C "cmd if @isdir==FALSE /C del "@FILE""
FORFILES /P D:\Channel_Programm_Air\XPression\DAY\07_Ёо«м\ /M *.* /S /D -14 /C "cmd if @isdir==FALSE /C del "@FILE""
FORFILES /P D:\Channel_Programm_Air\XPression\DAY\08_ ўЈгбв\ /M *.* /S /D -14 /C "cmd if @isdir==FALSE /C del "@FILE""
FORFILES /P D:\Channel_Programm_Air\XPression\DAY\09_бҐ­впЎам\ /M *.* /S /D -14 /C "cmd if @isdir==FALSE /C del "@FILE"" 
FORFILES /P D:\Channel_Programm_Air\XPression\DAY\10_®ЄвпЎам\ /M *.* /S /D -14 /C "cmd if @isdir==FALSE /C del "@FILE"" 
FORFILES /P D:\Channel_Programm_Air\XPression\DAY\11_­®пЎам\ /M *.* /S /D -14 /C "cmd if @isdir==FALSE /C del "@FILE""
FORFILES /P D:\Channel_Programm_Air\XPression\DAY\12_¤ҐЄ Ўам\ /M *.* /S /D -14 /C "cmd if @isdir==FALSE /C del "@FILE""
FORFILES /P D:\Channel_Programm_Air\XPression\„Ґ­м\’Ґ¬ вЁзҐбЄЁҐ_и ЇЄЁ\ /M *.* /S /D -14 /C "cmd if @isdir==FALSE /C del "@FILE""
FORFILES /P D:\Channel_Programm_Air\XPression\—ќ‡\‚Ё¤Ґ®_¤«п_ ­®­б \ /M *.* /S /D -14 /C "cmd if @isdir==FALSE /C del "@FILE""
